export {}; 
const countries = [
  { "name": "France", "visited": false },
  { "name": "Spain", "visited": false },
  { "name": "Canada", "visited": false },
  { "name": "United States", "visited": false },
  { "name": "Italy", "visited": false },
  { "name": "China", "visited": false },
  { "name": "United Kingdom", "visited": false },
  { "name": "Germany", "visited": false },
  { "name": "Japan", "visited": false },
  { "name": "Thailand", "visited": false },
  { "name": "Mexico", "visited": false },
  { "name": "Greece", "visited": false },
  { "name": "Turkey", "visited": false },
  { "name": "Australia", "visited": false },
  { "name": "Switzerland", "visited": false },
  { "name": "Malaysia", "visited": false },
  { "name": "Singapore", "visited": false },
  { "name": "South Korea", "visited": false },
  { "name": "New Zealand", "visited": false },
  { "name": "Hong Kong", "visited": false },
  { "name": "Vietnam", "visited": false },
  { "name": "Brazil", "visited": false },
  { "name": "Indonesia", "visited": false },
  { "name": "Philippines", "visited": false },
  { "name": "Sri Lanka", "visited": false },
  { "name": "Maldives", "visited": false },
  { "name": "Ireland", "visited": false },
  { "name": "Czech Republic", "visited": false },
  { "name": "Russia", "visited": false },
  { "name": "Bahamas", "visited": false },
  { "name": "Barbados", "visited": false },
  { "name": "Jamaica", "visited": false },
  { "name": "Cuba", "visited": false },
  { "name": "Puerto Rico", "visited": false },
  { "name": "Aruba", "visited": false }
];

export default countries; 
